### ISSUE TITLE
http redirect no longer working correctly in 3.41

### ISSUE THREAD

**Issue by seife** [schreibfaul1/ESP32-audioI2S#1126]
A working example: http://bestof80s.stream.laut.fm/best_of_80s
```
00:00:29>info    : connect to: "bestof80s.stream.laut.fm" on port 80 path "/best_of_80s"
00:00:29>info    : Connection has been established in 39 ms
00:00:29>lasthost: http://bestof80s.stream.laut.fm/best_of_80s
00:00:29>info    : icy-name: Best of 80s
00:00:29>station : Best of 80s
00:00:29>icyurl  : http://laut.fm/best_of_80s
00:00:29>info    : icy-genre:  80er
00:00:29>info    : icy-bitrate: 128000
00:00:29>bitrate : 128000
00:00:29>info    : MP3Decoder has been initialized
00:00:29>info    : stream ready
00:00:29>info    : syncword found at pos 191
00:00:29>info    : syncword found at pos 0
00:00:29>info    : MPEG-1 Layer III
00:00:29>info    : Channels: 2
00:00:29>info    : SampleRate: 44100
00:00:29>info    : BitsPerSample: 16
00:00:29>info    : BitRate: 128000
```
non-working http://stream.laut.fm/best_of_80s, which redirects to the other one:
```
> curl -v http://stream.laut.fm/best_of_80s
* Host stream.laut.fm:80 was resolved.
* IPv6: (none)
* IPv4: 80.255.8.253
*   Trying 80.255.8.253:80...
* Connected to stream.laut.fm (80.255.8.253) port 80
* using HTTP/1.x
> GET /best_of_80s HTTP/1.1
> Host: stream.laut.fm
> User-Agent: curl/8.14.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 302 Found
< Date: Tue, 05 Aug 2025 12:55:19 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 137
< Connection: keep-alive
< Location: http://bestof80s.stream.laut.fm/best_of_80s?t302=2025-08-05_12-55-19&uuid=f555f5f8-541c-46e3-8366-65114b1a18ae
< 
<a href="http://bestof80s.stream.laut.fm/best_of_80s?t302=2025-08-05_12-55-19&amp;uuid=f555f5f8-541c-46e3-8366-65114b1a18ae">Found</a>.
```
with ESP32-audioI2S:
```
00:03:03>info    : connect to: "stream.laut.fm" on port 80 path "/best_of_80s"
00:03:03>info    : Connection has been established in 36 ms
00:03:03>lasthost: http://stream.laut.fm/best_of_80s
00:03:03>info    : redirect to new host "http://bestof80s.stream.laut.fm/best_of_80s?t302=2025-08-05_12-56-04&uuid=5860ccb2-ad59-42a4-b278-491ec336458a"
00:03:03>info    : next URL: "http://bestof80s.stream.laut.fm/best_of_80s?t302=2025-08-05_12-56-04&uuid=5860ccb2-ad59-42a4-b278-491ec336458a"
00:03:03>info    : icy-name: Best of 80s
00:03:03>station : Best of 80s
00:03:03>icyurl  : http://laut.fm/best_of_80s
00:03:03>info    : icy-genre:  80er
00:03:03>info    : icy-bitrate: 128000
00:03:03>bitrate : 128000
00:03:03>info    : MP3Decoder has been initialized
00:03:03>info    : File-Size: 137
00:03:03>info    : file has no ID3 tag, skip metadata
00:03:03>info    : Audio-Length: 137
00:03:03>info    : stream ready
00:03:03>info    : mp3_decoder.cpp:1446: Header valid, but not enough data for next frame check. Possibly end of stream or false positive.
00:03:03>info    : mp3_decoder.cpp:1406: No syncword found in remaining buffer
00:03:03>info    : End of webstream: "http://stream.laut.fm/best_of_80s"
```
After some retries it eventually starts playing but with frequent errors and dropouts every second, as something seems to be out of sync:
```
00:07:58>info    : mp3_decoder.cpp:1635: MP3 invalid frameheader
00:07:58>info    : syncword found at pos 0
00:07:58>info    : MPEG-1 Layer III
00:07:58>info    : Channels: 2
00:07:58>info    : SampleRate: 44100
00:07:58>info    : BitsPerSample: 16
00:07:58>info    : BitRate: 128000
00:07:59>info    : mp3_decoder.cpp:1635: MP3 invalid frameheader
00:07:59>info    : syncword found at pos 0
00:07:59>info    : MPEG-1 Layer III
00:07:59>info    : Channels: 2
00:07:59>info    : SampleRate: 44100
00:07:59>info    : BitsPerSample: 16
00:07:59>info    : BitRate: 128000
00:08:00>info    : mp3_decoder.cpp:1635: MP3 invalid frameheader
00:08:00>info    : syncword found at pos 0
00:08:00>info    : MPEG-1 Layer III
00:08:00>info    : Channels: 2
00:08:00>info    : SampleRate: 44100
00:08:00>info    : BitsPerSample: 16
00:08:00>info    : BitRate: 128000
```

**Comment by schreibfaul1** [comment]
Indeed, the redirection no longer worked, I have corrected it.

**Comment by stef-ladefense** [comment]
sorry, but not work too with 3.4.1a

**Comment by seife** [comment]
It looks like it is not only redirection, e.g. http://kea.cdnstream.com:80/1897_128 which is not redirecting at all still gets me the "MP3 invalid frameheader" dropouts once per second.
so it looks like all MP3 streams are broken right now.

**Comment by seife** [comment]
seems fixed with 3.4.1c
